# Generated by Django 4.2.13 on 2025-12-27 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchasing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.07, help_text='0.00 para Exento, 0.07 para ITBMS estándar', max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='apply_retention',
            field=models.BooleanField(default=True, help_text='Aplica retención según tipo de proveedor (50% Local / 100% Extranjero)'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='is_gross_up',
            field=models.BooleanField(default=False, help_text='Solo Extranjeros: La empresa asume el impuesto. El precio unitario se considera neto.', verbose_name='Grossing Up'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='payable_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total a Pagar (Neto)'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='retention_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='ITBMS Retenido'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='ITBMS Total'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='dv',
            field=models.CharField(blank=True, max_length=2, verbose_name='DV'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='ruc',
            field=models.CharField(blank=True, max_length=20, verbose_name='RUC/Tax ID'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(choices=[('Local', 'Local (Panamá)'), ('Foreign', 'Extranjero (Internacional)')], default='Local', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('Draft', 'Borrador'), ('Submitted', 'Confirmado'), ('Received', 'Recibido (Parcial/Total)'), ('Completed', 'Cerrado/Pagado'), ('Cancelled', 'Anulado')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Factura'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Razón Social'),
        ),
    ]
