# Generated by Django 4.2.13 on 2025-12-27 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Razón Social / Nombre')),
                ('ruc', models.CharField(help_text='Registro Único de Contribuyente', max_length=20, unique=True, verbose_name='RUC')),
                ('dv', models.CharField(help_text='Dígito Verificador', max_length=2, verbose_name='DV')),
                ('taxpayer_type', models.CharField(choices=[('Natural', 'Persona Natural'), ('Juridico', 'Persona Jurídica'), ('Exento', 'Exento / Gobierno'), ('Extranjero', 'Extranjero')], default='Juridico', max_length=15)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True, verbose_name='Dirección Física')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('shipping_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Borrador'), ('Confirmed', 'Confirmado'), ('Shipped', 'Enviado'), ('Invoiced', 'Facturado'), ('Cancelled', 'Anulado')], default='Draft', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='ITBMS Total')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='SOItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.07, help_text='0.07 para 7%', max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_items', to='inventory.product')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesorder')),
            ],
        ),
    ]
