# Generated by Django 4.2.13 on 2025-12-27 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='shipping_date',
        ),
        migrations.RemoveField(
            model_name='salesorder',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='cufe',
            field=models.CharField(blank=True, help_text='Código Único de Factura Electrónica', max_length=100, null=True, verbose_name='CUFE'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='dgi_status',
            field=models.CharField(choices=[('NotSent', 'No Enviado'), ('Sent', 'Enviado al PAC'), ('Authorized', 'Autorizado (CUFE Generado)'), ('Rejected', 'Rechazado')], default='NotSent', max_length=20),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Descuento Total'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='qr_data',
            field=models.TextField(blank=True, help_text='Cadena para generar el QR', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='subtotal_exempt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Subtotal Exento'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='subtotal_taxable',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Subtotal Gravable'),
        ),
        migrations.AddField(
            model_name='soitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Descuento'),
        ),
        migrations.AddField(
            model_name='soitem',
            name='isc_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Impuesto Selectivo al Consumo (si aplica)', max_digits=5, verbose_name='Tasa ISC'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, verbose_name='Dirección Física (DGI)'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dv',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='DV'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ruc',
            field=models.CharField(help_text='Sin guiones para PJ', max_length=20, unique=True, verbose_name='RUC/NT'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='taxpayer_type',
            field=models.CharField(choices=[('Natural', 'Persona Natural'), ('Juridico', 'Persona Jurídica'), ('Exento', 'Exento / Zona Libre'), ('Extranjero', 'Extranjero / Pasaporte')], default='Juridico', max_length=15),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('Draft', 'Borrador'), ('Confirmed', 'Confirmado (Cotización)'), ('Invoiced', 'Facturado'), ('Cancelled', 'Anulado')], default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='ITBMS'),
        ),
        migrations.AlterField(
            model_name='soitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.07, help_text='0.07 para 7%, 0.10 para alcohol, etc.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='soitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario'),
        ),
    ]
