# Generated by Django 4.2.13 on 2025-12-27 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_customer_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contacto Principal'),
        ),
        migrations.AlterField(
            model_name='soitem',
            name='isc_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tasa ISC'),
        ),
        migrations.AlterField(
            model_name='soitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.07, help_text='0.07 para 7%', max_digits=5),
        ),
    ]
