# Generated by Django 4.2.13 on 2025-12-10 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('inventory', '0002_category_income_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='asset_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories_asset', to='accounting.account', verbose_name='Cuenta de Activo (Inventario)'),
        ),
        migrations.AddField(
            model_name='product',
            name='current_stock',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
