# Generated by Django 4.2.13 on 2025-12-18 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_category_asset_account_product_current_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_calculated', models.DateField(auto_now_add=True)),
                ('forecast_period_start', models.DateField()),
                ('forecast_period_end', models.DateField()),
                ('predicted_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confidence_score', models.FloatField(help_text='0 a 1. Confianza del modelo')),
                ('recommended_action', models.CharField(choices=[('Restock', 'Reabastecer Urgente'), ('Mantener', 'Nivel Óptimo'), ('Overstock', 'Exceso de Inventario')], default='Mantener', max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_forecasts', to='inventory.product')),
            ],
        ),
    ]
