# Generated by Django 4.2.13 on 2025-12-18 03:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='dv',
            field=models.CharField(default='00', help_text='Dígito Verificador', max_length=2, verbose_name='DV'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='ruc',
            field=models.CharField(default='000-000', help_text='Registro Único de Contribuyente', max_length=20, unique=True, verbose_name='RUC'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='taxpayer_type',
            field=models.CharField(choices=[('Natural', 'Persona Natural'), ('Juridico', 'Persona Jurídica'), ('Exento', 'Exento / Gobierno'), ('Extranjero', 'Extranjero')], default='Juridico', max_length=15),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='ITBMS Total'),
        ),
        migrations.AddField(
            model_name='soitem',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0.07, help_text='0.07 para 7%', max_digits=5),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, verbose_name='Dirección Física'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Razón Social / Nombre'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='status',
            field=models.CharField(choices=[('Draft', 'Borrador'), ('Confirmed', 'Confirmado'), ('Shipped', 'Enviado'), ('Invoiced', 'Facturado'), ('Cancelled', 'Anulado')], default='Draft', max_length=20),
        ),
    ]
